export const LOAD_COMMUNITIES_REQUEST = 'LOAD_COMMUNITIES_REQUEST';
export const LOAD_COMMUNITIES_SUCCESS = 'LOAD_COMMUNITIES_SUCCESS';
export const LOAD_COMMUNITIES_FAILURE = 'LOAD_COMMUNITIES_FAILURE';
