export const TEST = 'TEST'
export const TEST_ASYNC = 'TEST_ASYNC'

export const LOAD_COMMUNITIES_REQUEST = 'LOAD_COMMUNITIES_REQUEST'
export const LOAD_COMMUNITIES_SUCCESS = 'LOAD_COMMUNITIES_SUCCESS'
export const LOAD_COMMUNITIES_FAILURE = 'LOAD_COMMUNITIES_FAILURE'

export const LOAD_AWESOME_PEOPLE_REQUEST = 'LOAD_AWESOME_PEOPLE_REQUEST'
export const LOAD_AWESOME_PEOPLE_SUCCESS = 'LOAD_AWESOME_PEOPLE_SUCCESS'
export const LOAD_AWESOME_PEOPLE_FAILURE = 'LOAD_AWESOME_PEOPLE_FAILURE'

