// TODO: move all of these into a STREAM object
export const ADD_NEW_IDS_TO_RESULT = 'ADD_NEW_IDS_TO_RESULT'

export const LOAD_STREAM = 'LOAD_STREAM'
export const LOAD_STREAM_REQUEST = 'LOAD_STREAM_REQUEST'
export const LOAD_STREAM_SUCCESS = 'LOAD_STREAM_SUCCESS'
export const LOAD_STREAM_FAILURE = 'LOAD_STREAM_FAILURE'

export const LOAD_NEXT_CONTENT = 'LOAD_NEXT_CONTENT'
export const LOAD_NEXT_CONTENT_REQUEST = 'LOAD_NEXT_CONTENT_REQUEST'
export const LOAD_NEXT_CONTENT_SUCCESS = 'LOAD_NEXT_CONTENT_SUCCESS'
export const LOAD_NEXT_CONTENT_FAILURE = 'LOAD_NEXT_CONTENT_FAILURE'

// Should these be `POST.JSON, POST.FORM` instead?
export const POST_JSON = 'POST_JSON'
export const POST_FORM = 'POST_FORM'

export const REQUESTER = {
  PAUSE: 'REQUESTER.PAUSE',
  UNPAUSE: 'REQUESTER.UNPAUSE',
}

export const HEAD = 'HEAD'
export const HEAD_REQUEST = 'HEAD_REQUEST'
export const HEAD_SUCCESS = 'HEAD_SUCCESS'
export const HEAD_FAILURE = 'HEAD_FAILURE'

export const SET_LAYOUT_MODE = 'SET_LAYOUT_MODE'

export const ALERT = {
  OPEN: 'ALERT.OPEN',
  CLOSE: 'ALERT.CLOSE',
}

export const AUTHENTICATION = {
  FORGOT_PASSWORD: 'AUTHENTICATION.FORGOT_PASSWORD',
  SCHEDULE_REFRESH: 'AUTHENTICATION.SCHEDULE_REFRESH',
  CANCEL_REFRESH: 'AUTHENTICATION.CANCEL_REFRESH',
  LOGOUT: 'AUTHENTICATION.LOGOUT',

  REFRESH: 'AUTHENTICATION.REFRESH',
  REFRESH_REQUEST: 'AUTHENTICATION.REFRESH_REQUEST',
  REFRESH_SUCCESS: 'AUTHENTICATION.REFRESH_SUCCESS',
  REFRESH_FAILURE: 'AUTHENTICATION.REFRESH_FAILURE',

  USER: 'AUTHENTICATION.USER',
  USER_REQUEST: 'AUTHENTICATION.USER_REQUEST',
  USER_SUCCESS: 'AUTHENTICATION.USER_SUCCESS',
  USER_FAILURE: 'AUTHENTICATION.USER_FAILURE',
}

export const BEACONS = {
  LAST_DISCOVER_VERSION: 'BEACONS.LAST_DISCOVER_VERSION',
  LAST_FOLLOWING_VERSION: 'BEACONS.LAST_FOLLOWING_VERSION',
  LAST_STARRED_VERSION: 'BEACONS.LAST_STARRED_VERSION',
}

export const COMMENT = {
  CREATE: 'COMMENT.CREATE',
  CREATE_REQUEST: 'COMMENT.CREATE_REQUEST',
  CREATE_SUCCESS: 'COMMENT.CREATE_SUCCESS',
  CREATE_FAILURE: 'COMMENT.CREATE_FAILURE',

  DELETE: 'COMMENT.DELETE',
  DELETE_REQUEST: 'COMMENT.DELETE_REQUEST',
  DELETE_SUCCESS: 'COMMENT.DELETE_SUCCESS',
  DELETE_FAILURE: 'COMMENT.DELETE_FAILURE',

  EDITABLE: 'COMMENT.EDITABLE',
  EDITABLE_REQUEST: 'COMMENT.EDITABLE_REQUEST',
  EDITABLE_SUCCESS: 'COMMENT.EDITABLE_SUCCESS',
  EDITABLE_FAILURE: 'COMMENT.EDITABLE_FAILURE',

  FLAG: 'COMMENT.FLAG',
  FLAG_REQUEST: 'COMMENT.FLAG_REQUEST',
  FLAG_SUCCESS: 'COMMENT.FLAG_SUCCESS',
  FLAG_FAILURE: 'COMMENT.FLAG_FAILURE',

  UPDATE: 'COMMENT.UPDATE',
  UPDATE_REQUEST: 'COMMENT.UPDATE_REQUEST',
  UPDATE_SUCCESS: 'COMMENT.UPDATE_SUCCESS',
  UPDATE_FAILURE: 'COMMENT.UPDATE_FAILURE',

  TOGGLE_EDITING: 'COMMENT.TOGGLE_EDITING',
}

export const EDITOR = {
  APPEND_TEXT: 'EDITOR.APPEND_TEXT',
  CLEAR_APPENDED_TEXT: 'EDITOR.CLEAR_APPENDED_TEXT',
}

export const EMOJI = {
  LOAD: 'EMOJI.LOAD',
  LOAD_REQUEST: 'EMOJI.LOAD_REQUEST',
  LOAD_SUCCESS: 'EMOJI.LOAD_SUCCESS',
  LOAD_FAILURE: 'EMOJI.LOAD_FAILURE',
}

export const INVITATIONS = {
  GET_EMAIL: 'INVITATIONS.GET_EMAIL',
  GET_EMAIL_REQUEST: 'INVITATIONS.GET_EMAIL_REQUEST',
  GET_EMAIL_SUCCESS: 'INVITATIONS.GET_EMAIL_SUCCESS',
  GET_EMAIL_FAILURE: 'INVITATIONS.GET_EMAIL_FAILURE',

  INVITE: 'INVITATIONS.INVITE',
  INVITE_REQUEST: 'INVITATIONS.INVITE_REQUEST',
  INVITE_SUCCESS: 'INVITATIONS.INVITE_SUCCESS',
  INVITE_FAILURE: 'INVITATIONS.INVITE_FAILURE',
}

export const MODAL = {
  OPEN: 'MODAL.OPEN',
  CLOSE: 'MODAL.CLOSE',
  TOGGLE_NOTIFICATIONS: 'MODAL.TOGGLE_NOTIFICATIONS',
}

export const OMNIBAR = {
  OPEN: 'OMNIBAR.OPEN',
  CLOSE: 'OMNIBAR.CLOSE',
}

export const POST = {
  AUTO_COMPLETE: 'POST.AUTO_COMPLETE',
  AUTO_COMPLETE_REQUEST: 'POST.AUTO_COMPLETE_REQUEST',
  AUTO_COMPLETE_SUCCESS: 'POST.AUTO_COMPLETE_SUCCESS',
  AUTO_COMPLETE_FAILURE: 'POST.AUTO_COMPLETE_FAILURE',

  AUTO_COMPLETE_CLEAR: 'POST.AUTO_COMPLETE_CLEAR',

  COMMENT: 'POST.COMMENT',
  COMMENT_REQUEST: 'POST.COMMENT_REQUEST',
  COMMENT_SUCCESS: 'POST.COMMENT_SUCCESS',
  COMMENT_FAILURE: 'POST.COMMENT_FAILURE',

  CREATE: 'POST.CREATE',
  CREATE_REQUEST: 'POST.CREATE_REQUEST',
  CREATE_SUCCESS: 'POST.CREATE_SUCCESS',
  CREATE_FAILURE: 'POST.CREATE_FAILURE',

  DELETE: 'POST.DELETE',
  DELETE_REQUEST: 'POST.DELETE_REQUEST',
  DELETE_SUCCESS: 'POST.DELETE_SUCCESS',
  DELETE_FAILURE: 'POST.DELETE_FAILURE',

  DETAIL: 'POST.DETAIL',
  DETAIL_REQUEST: 'POST.DETAIL_REQUEST',
  DETAIL_SUCCESS: 'POST.DETAIL_SUCCESS',
  DETAIL_FAILURE: 'POST.DETAIL_FAILURE',

  EDITABLE: 'POST.EDITABLE',
  EDITABLE_REQUEST: 'POST.EDITABLE_REQUEST',
  EDITABLE_SUCCESS: 'POST.EDITABLE_SUCCESS',
  EDITABLE_FAILURE: 'POST.EDITABLE_FAILURE',

  FLAG: 'POST.FLAG',
  FLAG_REQUEST: 'POST.FLAG_REQUEST',
  FLAG_SUCCESS: 'POST.FLAG_SUCCESS',
  FLAG_FAILURE: 'POST.FLAG_FAILURE',

  LOVE: 'POST.LOVE',
  LOVE_REQUEST: 'POST.LOVE_REQUEST',
  LOVE_SUCCESS: 'POST.LOVE_SUCCESS',
  LOVE_FAILURE: 'POST.LOVE_FAILURE',

  PERSIST: 'POST.PERSIST',

  // used for previewing an embed
  POST_PREVIEW: 'POST.POST_PREVIEW',
  POST_PREVIEW_REQUEST: 'POST.POST_PREVIEW_REQUEST',
  POST_PREVIEW_SUCCESS: 'POST.POST_PREVIEW_SUCCESS',
  POST_PREVIEW_FAILURE: 'POST.POST_PREVIEW_FAILURE',

  UPDATE: 'POST.UPDATE',
  UPDATE_REQUEST: 'POST.UPDATE_REQUEST',
  UPDATE_SUCCESS: 'POST.UPDATE_SUCCESS',
  UPDATE_FAILURE: 'POST.UPDATE_FAILURE',

  // TODO: does not conform to my OCD
  // adding an image block stuff
  TMP_IMAGE_CREATED: 'POST.TMP_IMAGE_CREATED',
  IMAGE_BLOCK_CREATED: 'POST.IMAGE_BLOCK_CREATED',
  SAVE_IMAGE: 'POST.SAVE_IMAGE',
  SAVE_IMAGE_REQUEST: 'POST.SAVE_IMAGE_REQUEST',
  SAVE_IMAGE_SUCCESS: 'POST.SAVE_IMAGE_SUCCESS',
  SAVE_IMAGE_FAILURE: 'POST.SAVE_IMAGE_FAILURE', REPOST_FAILURE: 'POST.REPOST_FAILURE',

  TOGGLE_COMMENTS: 'POST.TOGGLE_COMMENTS',
  TOGGLE_EDITING: 'POST.TOGGLE_EDITING',
  TOGGLE_LOVERS: 'POST.TOGGLE_LOVERS',
  TOGGLE_REPOSTERS: 'POST.TOGGLE_REPOSTERS',
  TOGGLE_REPOSTING: 'POST.TOGGLE_REPOSTING',
}

export const PROFILE = {
  AVAILABILITY: 'PROFILE.AVAILABILITY',
  AVAILABILITY_REQUEST: 'PROFILE.AVAILABILITY_REQUEST',
  AVAILABILITY_SUCCESS: 'PROFILE.AVAILABILITY_SUCCESS',
  AVAILABILITY_FAILURE: 'PROFILE.AVAILABILITY_FAILURE',

  DELETE: 'PROFILE.DELETE',
  DELETE_REQUEST: 'PROFILE.DELETE_REQUEST',
  DELETE_SUCCESS: 'PROFILE.DELETE_SUCCESS',
  DELETE_FAILURE: 'PROFILE.DELETE_FAILURE',

  DETAIL: 'PROFILE.DETAIL',
  DETAIL_REQUEST: 'PROFILE.DETAIL_REQUEST',
  DETAIL_SUCCESS: 'PROFILE.DETAIL_SUCCESS',
  DETAIL_FAILURE: 'PROFILE.DETAIL_FAILURE',

  EXPORT: 'PROFILE.EXPORT',
  EXPORT_REQUEST: 'PROFILE.EXPORT_REQUEST',
  EXPORT_SUCCESS: 'PROFILE.EXPORT_SUCCESS',
  EXPORT_FAILURE: 'PROFILE.EXPORT_FAILURE',

  LOAD: 'PROFILE.LOAD',
  LOAD_REQUEST: 'PROFILE.LOAD_REQUEST',
  LOAD_SUCCESS: 'PROFILE.LOAD_SUCCESS',
  LOAD_FAILURE: 'PROFILE.LOAD_FAILURE',

  REQUEST_INVITE: 'PROFILE.REQUEST_INVITE',
  REQUEST_INVITE_REQUEST: 'PROFILE.REQUEST_INVITE_REQUEST',
  REQUEST_INVITE_SUCCESS: 'PROFILE.REQUEST_INVITE_SUCCESS',
  REQUEST_INVITE_FAILURE: 'PROFILE.REQUEST_INVITE_FAILURE',

  SAVE: 'PROFILE.SAVE',
  SAVE_REQUEST: 'PROFILE.SAVE_REQUEST',
  SAVE_SUCCESS: 'PROFILE.SAVE_SUCCESS',
  SAVE_FAILURE: 'PROFILE.SAVE_FAILURE',

  SAVE_AVATAR: 'PROFILE.SAVE_AVATAR',
  SAVE_AVATAR_REQUEST: 'PROFILE.SAVE_AVATAR_REQUEST',
  SAVE_AVATAR_SUCCESS: 'PROFILE.SAVE_AVATAR_SUCCESS',
  SAVE_AVATAR_FAILURE: 'PROFILE.SAVE_AVATAR_FAILURE',

  SAVE_COVER: 'PROFILE.SAVE_COVER',
  SAVE_COVER_REQUEST: 'PROFILE.SAVE_COVER_REQUEST',
  SAVE_COVER_SUCCESS: 'PROFILE.SAVE_COVER_SUCCESS',
  SAVE_COVER_FAILURE: 'PROFILE.SAVE_COVER_FAILURE',

  SIGNUP: 'PROFILE.SIGNUP',
  SIGNUP_SUCCESS: 'PROFILE.SIGNUP_SUCCESS',

  TMP_AVATAR_CREATED: 'PROFILE.TMP_AVATAR_CREATED',
  TMP_COVER_CREATED: 'PROFILE.TMP_COVER_CREATED',
}

export const RELATIONSHIPS = {
  BATCH_UPDATE_INTERNAL: 'RELATIONSHIPS.BATCH_UPDATE_INTERNAL',
  UPDATE_INTERNAL: 'RELATIONSHIPS.UPDATE_INTERNAL',

  UPDATE: 'RELATIONSHIPS.UPDATE',
  UPDATE_REQUEST: 'RELATIONSHIPS.UPDATE_REQUEST',
  UPDATE_SUCCESS: 'RELATIONSHIPS.UPDATE_SUCCESS',
  UPDATE_FAILURE: 'RELATIONSHIPS.UPDATE_FAILURE',
}

export const TRACK = {
  EVENT: 'TRACK.EVENT',
}

export const GUI = {
  NOTIFICATIONS_TAB: 'GUI.NOTIFICATIONS_TAB',
  SET_IS_OFFSET_LAYOUT: 'GUI.SET_IS_OFFSET_LAYOUT',
  BIND_DISCOVER_KEY: 'DISCOVER.BIND_DISCOVER_KEY',
  SET_SCROLL: 'GUI.SET_SCROLL',
  SET_FOLLOWING_TAB: 'GUI.SET_FOLLOWING_TAB',
}

